### ISSUE TITLE
`wasi:http/proxy` definition is incorrect

### ISSUE THREAD

**Issue by rylev** [JAFLabs/wa.dev-issues#7]
It appears that [`wasi:http/proxy` world definition](https://wa.dev/wasi:http) is incorrect in that it is missing the `wasi:random/random` import which [appears to be required](https://github.com/WebAssembly/wasi-http/blob/a81c61fc584278f801393b22289840a439e51f50/wit/proxy.wit#L8).

**Comment by macovedj** [comment]
Thanks for letting us know!  Will look into it!

**Comment by calvinrp** [comment]
We need to reset the `wasi` registry on `wa.dev` and republish the packages. Users will need to do `warg reset` afterwards if they have `wasi` packages previously downloaded.

`wasi:random` package's Wasm binary internally states its package as package `wasi:random@0.2.0-rc-2023-11-10`; instead of `0.2.0` but was published to Warg as `0.2.0`. Mishap when publishing a few months ago.

`wasi:http` is missing the import `wasi:random@0.2.0` in the proxy world and also includes the world `imports` which looks like it is on [`main` branch](https://github.com/WebAssembly/wasi-http/blob/main/wit/proxy.wit) but not on the tag `0.2.0`.

The only way to fix, is to do registry reset and republish all the `wasi` packages.

Will message again when fixed. Apologies.

**Comment by calvinrp** [comment]
Fixed. `warg reset` is needed on your local CLI if you have previously cached packages.
